---
title: "Zebrafish_Adult_Annotation"
output: html_document
date: "2025-06-11"
---

```{r}

library(Seurat)
library(tidyverse)

heart <- readRDS('scRNA-seq-chamber.rds') # from Li et al., Nature Communications (2025)
zcm_li_atr <- subset(heart, idents='Cardiomyocytes (A)')
zcm_li <- subset(heart, idents=c('Cardiomyocytes (A)', 'Cardiomyocytes (V)'))

zcm_li_atr <- NormalizeData(zcm_li_atr)
zcm_li_atr <- FindVariableFeatures(zcm_li_atr)
zcm_li_atr <- ScaleData(zcm_li_atr)
zcm_li_atr <- RunPCA(zcm_li_atr)
zcm_li_atr <- FindNeighbors(zcm_li_atr, dims=1:20)
zcm_li_atr <- RunUMAP(zcm_li_atr, dims=1:20)
zcm_li_atr <- FindClusters(zcm_li_atr, resolution=0.25)

zccs_li <- subset(zcm_li_atr, idents='2')
zccs_li <- NormalizeData(zccs_li)
zccs_li <- FindVariableFeatures(zccs_li)
zccs_li <- ScaleData(zccs_li)
zccs_li <- RunPCA(zccs_li)
zccs_li <- FindNeighbors(zccs_li, dims=1:20)
zccs_li <- RunUMAP(zccs_li, dims=1:20)
zccs_li <- FindClusters(zccs_li, resolution=1)

zccs_li <- SetIdent(zccs_li, WhichCells(zccs_li, idents='6'), 'AVC')
zccs_li <- SetIdent(zccs_li, WhichCells(zccs_li, idents='AVC', invert=T), 'SA node')
zccs_li$sub_ccs <- Idents(zccs_li)

zcm_li <- NormalizeData(zcm_li)
zcm_li <- FindVariableFeatures(zcm_li)
zcm_li <- ScaleData(zcm_li)
zcm_li <- RunPCA(zcm_li)
zcm_li <- FindNeighbors(zcm_li, dims=1:20)
zcm_li <- RunUMAP(zcm_li, dims=1:20)

zcm_li <- SetIdent(zcm_li, WhichCells(zcm_li, idents='Cardiomyocytes (V)'), 'vCM')
zcm_li <- SetIdent(zcm_li, WhichCells(zcm_li, idents='Cardiomyocytes (A)'), 'aCM')
zcm_li <- SetIdent(zcm_li, WhichCells(zccs_li, idents='AVC'), 'AVC')
zcm_li <- SetIdent(zcm_li, WhichCells(zccs_li, idents='SA node'), 'SA node')
zcm_li$sub_ccs <- Idents(zcm_li)

```

# plot figure
```{r}

zcm_li_atr <- SetIdent(zcm_li_atr, WhichCells(zcm_li_atr, idents='2', invert=T), 'aCM')
zcm_li_atr <- SetIdent(zcm_li_atr, WhichCells(zccs_li, idents='AVC'), 'AVC')
zcm_li_atr <- SetIdent(zcm_li_atr, WhichCells(zccs_li, idents='SA node'), 'SA node')

fig <- DimPlot(zcm_li_atr, cols=c("#861d21", "#F4C542", "#5E6367"), pt.size=0.6) & NoAxes() & theme(plot.title=element_blank(), legend.text = element_text(size=16))

ggsave('acm_subcluster_umap.tiff', fig, dpi=600, height=7, width=11)

fig <- DotPlot(
  zcm_li_atr,
  rev(c('atp1b3b',
    'COLEC10',
    'shox2',
    'vsnl1a',
    'hcn1',
    'hcn4',
    'tbx2a',
    'tbx2b',
    'bmp4',
    'cx36.7',
    'myh7l',
    'nppa',
    'gja5a'
  )),
  cols = c('whitesmoke', '#ad2831'),
  dot.scale = 10,
  dot.min = -0.10
) &
  scale_size(breaks = c(0, 20, 40, 60, 80, 100)) &
  theme(
    axis.title = element_blank(),
    axis.text.y = element_text(face='italic'),
    panel.border = element_rect(color = "black", fill = NA, size = 1),
    axis.line = element_blank(),
    axis.text.x=element_text(angle=45, hjust=1, vjust=1)
  ) & coord_flip() & guides(size = guide_legend(order=1, title='Percent Expression')) &
  scale_x_discrete(labels = function(x) ifelse(x == "COLEC10", "colec10", x))

ggsave('san_avc_markers_dotplot.tiff', fig, dpi=600, width=7, height=6)

```